package com.agribridge.backend.entity.enums;

public enum OrderStatusEnum {
    PENDING_SUPPLIER_CONFIRMATION,
    PENDING,
    PENDING_PAYMENT,
    PENDING_DEPOSIT,
    DEPOSIT_PAID_WAITING_SUPPLIER_CONFIRM,
    PAID_WAITING_SUPPLIER_CONFIRM,
    SUPPLIER_CONFIRMED,
    PREPARING,
    READY_TO_SHIP,
    CONFIRMED,
    SHIPPING,
    DELIVERED,
    WAITING_FINAL_PAYMENT,
    WAITING_BUYER_CONFIRM,
    COMPLETED,
    CANCELLED,
    DISPUTED,
    REFUND_PENDING,
    PARTIALLY_REFUNDED,
    REFUNDED
}
