DECLARE @now DATETIME2 = SYSUTCDATETIME();

INSERT INTO categories (name, description, user_id, created_at)
SELECT seed.name, seed.description, NULL, @now
FROM (VALUES
    (N'Rau củ quả', N'Danh mục cha demo cho rau củ quả'),
    (N'Trái cây', N'Danh mục cha demo cho trái cây'),
    (N'Gạo và ngũ cốc', N'Danh mục cha demo cho gạo và ngũ cốc'),
    (N'Thịt và gia cầm', N'Danh mục cha demo cho thịt và gia cầm'),
    (N'Thủy sản', N'Danh mục cha demo cho thủy sản'),
    (N'Hải sản khô', N'Danh mục cha demo cho hải sản khô'),
    (N'Trứng và sản phẩm từ trứng', N'Danh mục cha demo cho trứng'),
    (N'Sữa và sản phẩm từ sữa', N'Danh mục cha demo cho sữa'),
    (N'Đồ khô và gia vị', N'Danh mục cha demo cho đồ khô và gia vị'),
    (N'Nông sản chế biến', N'Danh mục cha demo cho nông sản chế biến'),
    (N'Cây giống và vật tư nông nghiệp', N'Danh mục cha demo cho cây giống và vật tư'),
    (N'Rau ăn lá', N'Rau củ quả'),
    (N'Rau gia vị', N'Rau củ quả'),
    (N'Củ quả', N'Rau củ quả'),
    (N'Nấm', N'Rau củ quả'),
    (N'Rau hữu cơ', N'Rau củ quả'),
    (N'Trái cây nhiệt đới', N'Trái cây'),
    (N'Trái cây nhập khẩu', N'Trái cây'),
    (N'Trái cây theo mùa', N'Trái cây'),
    (N'Trái cây sấy', N'Trái cây'),
    (N'Gạo trắng', N'Gạo và ngũ cốc'),
    (N'Gạo thơm', N'Gạo và ngũ cốc'),
    (N'Gạo lứt', N'Gạo và ngũ cốc'),
    (N'Nếp', N'Gạo và ngũ cốc'),
    (N'Bắp', N'Gạo và ngũ cốc'),
    (N'Đậu các loại', N'Gạo và ngũ cốc'),
    (N'Hạt dinh dưỡng', N'Gạo và ngũ cốc'),
    (N'Thịt heo', N'Thịt và gia cầm'),
    (N'Thịt bò', N'Thịt và gia cầm'),
    (N'Thịt gà', N'Thịt và gia cầm'),
    (N'Thịt vịt', N'Thịt và gia cầm'),
    (N'Thịt dê', N'Thịt và gia cầm'),
    (N'Sản phẩm sơ chế', N'Thịt và gia cầm'),
    (N'Cá nước ngọt', N'Thủy sản'),
    (N'Cá biển', N'Thủy sản'),
    (N'Tôm', N'Thủy sản'),
    (N'Cua ghẹ', N'Thủy sản'),
    (N'Mực bạch tuộc', N'Thủy sản'),
    (N'Nghêu sò ốc', N'Thủy sản'),
    (N'Hải sản đông lạnh', N'Thủy sản'),
    (N'Cá khô', N'Hải sản khô'),
    (N'Mực khô', N'Hải sản khô'),
    (N'Tôm khô', N'Hải sản khô'),
    (N'Khô rim/chế biến', N'Hải sản khô'),
    (N'Trứng gà', N'Trứng và sản phẩm từ trứng'),
    (N'Trứng vịt', N'Trứng và sản phẩm từ trứng'),
    (N'Trứng cút', N'Trứng và sản phẩm từ trứng'),
    (N'Trứng muối', N'Trứng và sản phẩm từ trứng'),
    (N'Sữa tươi', N'Sữa và sản phẩm từ sữa'),
    (N'Sữa chua', N'Sữa và sản phẩm từ sữa'),
    (N'Phô mai', N'Sữa và sản phẩm từ sữa'),
    (N'Sản phẩm từ sữa dê/bò', N'Sữa và sản phẩm từ sữa'),
    (N'Muối', N'Đồ khô và gia vị'),
    (N'Đường', N'Đồ khô và gia vị'),
    (N'Nước mắm', N'Đồ khô và gia vị'),
    (N'Mắm các loại', N'Đồ khô và gia vị'),
    (N'Tiêu', N'Đồ khô và gia vị'),
    (N'Ớt', N'Đồ khô và gia vị'),
    (N'Hành tỏi khô', N'Đồ khô và gia vị'),
    (N'Gia vị nấu ăn', N'Đồ khô và gia vị'),
    (N'Rau củ đóng gói', N'Nông sản chế biến'),
    (N'Trái cây đóng hộp', N'Nông sản chế biến'),
    (N'Mứt', N'Nông sản chế biến'),
    (N'Nước ép', N'Nông sản chế biến'),
    (N'Tinh bột', N'Nông sản chế biến'),
    (N'Sản phẩm lên men', N'Nông sản chế biến'),
    (N'Hạt giống', N'Cây giống và vật tư nông nghiệp'),
    (N'Cây giống', N'Cây giống và vật tư nông nghiệp'),
    (N'Phân bón', N'Cây giống và vật tư nông nghiệp'),
    (N'Đất trồng', N'Cây giống và vật tư nông nghiệp'),
    (N'Dụng cụ nông nghiệp', N'Cây giống và vật tư nông nghiệp')
) AS seed(name, description)
WHERE NOT EXISTS (
    SELECT 1 FROM categories c
    WHERE c.user_id IS NULL AND c.name = seed.name
);
